version: '3.8'
services:
  chrysedgeportal:
    image: chryscloud/chrysedgeportal:0.0.8
    build: web/
    depends_on:
      - chrysedgeserver
      - redis
    ports:
      - "8905:8905"
    networks:
      - chrysnet
  chrysedgeserver:
    image: chryscloud/chrysedgeserver:0.0.8
    build: server/
    restart: always
    depends_on:
      - redis
    entrypoint: /app/main
    # command: " -c /data/chrysalis/conf.yaml" # optional argument if not in data root folder of /data/chrysalis volume
    ports:
      - "8909:8909"
      - "50001:50001"
    volumes:
      - /data/chrysalis:/data/chrysalis
      - /var/run/docker.sock:/var/run/docker.sock
    networks: 
      - chrysnet
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    # volumes:
    #   - /data/chrysalis/redis:/data
    #   - ./redis.conf:/usr/local/etc/redis/redis.conf
    # command:
    #   - redis-server
    #   - /usr/local/etc/redis/redis.conf
  
    networks: 
      - chrysnet

networks:
  chrysnet:
    name: chrysnet
