definitions:
  api.JSONError:
    properties:
      code:
        type: integer
      message:
        type: string
    type: object
info:
  contact: {}
paths:
  /testmqtt/api/v1/devicestatus:
    get:
      consumes:
      - application/json
      description: Sends a mqtt message regarding device status
      parameters:
      - description: device name/id
        in: query
        name: deviceId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ""
        "417":
          description: test failed
          schema:
            $ref: '#/definitions/api.JSONError'
      security:
      - ApiKeyAuth: []
      summary: Testing mqtt device status
      tags:
      - MQTT
swagger: "2.0"
